# Generated by Django 2.1 on 2018-08-15 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(1800), django.core.validators.MinValueValidator(2150)], verbose_name='Год выпуска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(5000)], verbose_name='Колличество страниц'),
        ),
    ]
