# Generated by Django 2.1 on 2018-08-19 16:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, to='books.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=50000, verbose_name='Описание'),
        ),
    ]
